(async()=>{
  const results=[];
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const until=async(fn,timeout=20000)=>{const t=Date.now();while(!fn()){if(Date.now()-t>timeout)throw Error('Condition timed out: '+fn.toString());await wait(100);}};
  const check=(name,condition)=>{results.push({name,passed:!!condition});if(!condition)throw Error(name);};
  const realSend=send;
  try {
    await until(()=>state.ready&&state.regions.length>5,45000);
    check('local kiosk iframe loads with interactive regions',state.regions.length>5);
    let cursorResult;
    const originalReceive=window.receive;
    window.receive=m=>{if(m.type==='cursor_test_result')cursorResult=m;else originalReceive(m);};
    realSend('cursor_test',{x:420,y:310});
    await until(()=>cursorResult);
    check('actual macOS cursor reaches web coordinate (error '+cursorResult.error_px+'px)',cursorResult.passed);
    window.receive=originalReceive;
    check('800 supplied images available',SAMPLE_FILES.length===800);
    const doc=frameDocument();
    check('kiosk opens directly into menu',doc.getElementById('mega_order').style.display==='block');
    const item=doc.querySelector('[onclick^="option("]');item.click();
    await wait(350);
    check('kiosk menu click adds an order',$('kiosk').contentWindow.order_list.length===1);
    doc.getElementById('plus_1').click();
    check('cart plus increases quantity',$('kiosk').contentWindow.total_list[0]===2);
    doc.getElementById('minus_1').click();
    check('cart minus decreases quantity',$('kiosk').contentWindow.total_list[0]===1);
    doc.getElementById('delete_1').click();
    check('cart X removes item and hides stale row',$('kiosk').contentWindow.order_list.length===0&&doc.getElementById('order_1').style.display==='none'&&$('kiosk').contentWindow.total_list[1]===0);
    doc.querySelector('[id="커피프라페"]').click();
    check('coffee frappe handler adds the correct product',$('kiosk').contentWindow.order_list[0].name==='커피프라페');
    doc.getElementById('delete_1').click();item.click();await wait(600);
    const press=code=>keyHandler(new KeyboardEvent('keydown',{code,key:code==='Space'?' ':code,cancelable:true}));
    press('F8');check('physical-key pathway opens large cards without camera',!!switchBoard&&!state.camera);
    const frappeIndex=switchBoard.items.findIndex(r=>r.element.id==='커피프라페');
    check('frappe is reachable in button pathway',frappeIndex>=0);
    for(let i=0;i<frappeIndex;i++)press('ArrowRight');
    press('Enter');check('button selection requires confirmation',switchBoard.confirm);
    press('Enter');check('physical-key pathway orders frappe',$('kiosk').contentWindow.order_list.some(r=>r.name==='커피프라페'));
    $('kiosk').contentWindow.order_list=[];$('kiosk').contentWindow.open_order_list([]);item.click();await wait(600);
    switchView('sample');
    await until(()=>state.regions.length>0&&state.regions[0].key.startsWith('yolo'));
    check('real YOLO weights detect supplied image',state.regions.length>=5);
    check('YOLO boxes respect image viewport',state.regions.every(r=>r.w>0&&r.h>0&&r.x>=0&&r.y>=0));
    const sampleBoxes=state.regions.length;
    switchView('kiosk');await wait(600);
    $('regionMode').value='yolo';invalidateRegions();
    await until(()=>$('regionCount').textContent.includes('YOLO'),30000);
    check('real model also processes native kiosk snapshot',state.regions.every(r=>r.w>0&&r.h>0));
    const kioskBoxes=state.regions.length;
    $('regionMode').value='dom';invalidateRegions();await wait(500);
    // Head mode starts without gaze calibration or operating-system setup.
    $('clickMode').value='dwell';$('clickMode').onchange();
    $('clickMode').value='mouth';$('clickMode').onchange();
    const sent=[];send=(cmd,args={})=>sent.push({cmd,...args});
    receive({type:'started'});recenter();
    check('recenter requests internal head control',sent.some(m=>m.cmd==='recenter'));
    check('no macOS head-pointer settings control',!$('macHeadPointer')&&!$('headPointerGuide'));
    receive({type:'head_ready'});
    check('head tracking becomes usable without gaze profile',state.headReady);
    state.regions=visibleDomRegions();renderRegions();
    const target=state.regions.find(r=>r.element?.getAttribute('onclick')?.startsWith('option('));
    const trackEvent={type:'tracking',valid:true,x:target.x+target.w/2,y:target.y+target.h/2,reason:'테스트 입력',fps:30};
    for(let i=0;i<12;i++){receive(trackEvent);await wait(33);}
    check('tracking dispatches native cursor movement',sent.some(m=>m.cmd==='move_cursor'&&Math.abs(m.x-trackEvent.x)<2));
    check('gaze maps into kiosk target',state.active?.key===target.key&&!$('gaze').hidden);
    const beforeDwell=$('kiosk').contentWindow.total_list[0];
    $('clickMode').value='dwell';
    for(let i=0;i<42;i++){receive(i%8===7?{type:'tracking',valid:false,reason:'짧은 깜빡임'}:trackEvent);await wait(33);}
    await wait(500);
    const afterDwell=$('kiosk').contentWindow.total_list[0];
    check('dwell with brief face loss adds exactly one order',afterDwell===beforeDwell+1);
    receive(trackEvent);state.dwellStart=performance.now()-1300;receive(trackEvent);await wait(200);
    check('remaining gaze does not repeatedly order',$('kiosk').contentWindow.total_list[0]===afterDwell&&!!state.blockedRect);
    state.blockedRect=null;state.firedKey=null;
    $('clickMode').value='mouth';
    receive(trackEvent);await wait(50);
    const beforeMouth=$('kiosk').contentWindow.total_list[0];
    receive({type:'gesture_click',gesture:'jawopen',x:trackEvent.x,y:trackEvent.y});
    await wait(250);
    check('mouth open selects the pointed menu',$('kiosk').contentWindow.total_list[0]===beforeMouth+1);
    state.regions=visibleDomRegions();renderRegions();
    receive(trackEvent);await wait(50);
    const beforePaused=$('kiosk').contentWindow.total_list[0];
    pause();receive({type:'gesture_click',gesture:'jawopen'});await wait(150);
    check('mouth click is ignored while paused',$('kiosk').contentWindow.total_list[0]===beforePaused);
    pause();receive(trackEvent);await wait(50);
    receive({type:'tracking',valid:true,x:trackEvent.x,y:trackEvent.y,reason:'입벌림',fps:30,mouth:0.62,mouth_state:'조준'});
    check('mouth meter reflects the engine value',$('mouthFill').style.width==='62%');
    $('sensitivity').value='40';$('sensitivity').oninput();
    check('sensitivity slider reports a 0-1 value',sent.some(m=>m.cmd==='sensitivity'&&Math.abs(m.value-0.4)<1e-6));
    receive({type:'sensitivity',value:0.25});
    check('engine sensitivity updates the slider',$('sensitivity').value==='25'&&$('sensitivityValue').textContent==='25%');
    $('clickMode').value='mouth';
    receive({type:'tracking',valid:false,reason:'얼굴 미검출'});
    await wait(450);
    check('face loss clears target and cursor',state.active===null&&$('gaze').hidden);
    receive(trackEvent);pause();
    check('pause clears gaze',state.paused&&$('gaze').hidden);pause();
    recenter();check('recenter suspends selection until neutral is captured',!state.headReady);
    receive({type:'head_ready'});
    receive({type:'window_changed'});
    check('window changes do not require gaze calibration',state.headReady);
    receive({type:'stopped'});send=realSend;
    $('trackingHint').textContent='카메라를 켜고 고개로 메뉴를 선택하세요.';
    $('toast').hidden=true;switchView('kiosk');await wait(400);
    realSend('smoke_result',{passed:true,results,sample_boxes:sampleBoxes,kiosk_boxes:kioskBoxes});
  }catch(error){send=realSend;realSend('smoke_result',{passed:false,results,error:String(error),stack:error.stack,ready:state.ready,regions:state.regions.length,frameAccessible:!!$('kiosk').contentDocument});}
})();
