(async()=>{
  const results=[];
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const until=async(fn,timeout=20000)=>{const t=Date.now();while(!fn()){if(Date.now()-t>timeout)throw Error('Condition timed out: '+fn.toString());await wait(100);}};
  const check=(name,condition)=>{results.push({name,passed:!!condition});if(!condition)throw Error(name);};
  const realSend=send;
  try {
    await until(()=>state.ready&&state.regions.length>5,45000);
    check('local kiosk iframe loads with interactive regions',state.regions.length>5);
    let cursorResult;
    const originalReceive=window.receive;
    window.receive=m=>{if(m.type==='cursor_test_result')cursorResult=m;else originalReceive(m);};
    realSend('cursor_test',{x:420,y:310});
    await until(()=>cursorResult);
    check('actual macOS cursor reaches web coordinate (error '+cursorResult.error_px+'px)',cursorResult.passed);
    window.receive=originalReceive;
    check('800 supplied images available',SAMPLE_FILES.length===800);
    const doc=frameDocument();
    check('kiosk opens directly into menu',doc.getElementById('mega_order').style.display==='block');
    const item=doc.querySelector('[onclick^="option("]');item.click();
    await wait(350);
    check('kiosk menu click adds an order',$('kiosk').contentWindow.order_list.length===1);
    doc.getElementById('plus_1').click();
    check('cart plus increases quantity',$('kiosk').contentWindow.total_list[0]===2);
    doc.getElementById('minus_1').click();
    check('cart minus decreases quantity',$('kiosk').contentWindow.total_list[0]===1);
    doc.getElementById('delete_1').click();
    check('cart X removes item and hides stale row',$('kiosk').contentWindow.order_list.length===0&&doc.getElementById('order_1').style.display==='none'&&$('kiosk').contentWindow.total_list[1]===0);
    doc.querySelector('[id="커피프라페"]').click();
    check('coffee frappe handler adds the correct product',$('kiosk').contentWindow.order_list[0].name==='커피프라페');
    doc.getElementById('delete_1').click();item.click();await wait(600);
    const press=code=>keyHandler(new KeyboardEvent('keydown',{code,key:code==='Space'?' ':code,cancelable:true}));
    press('F8');check('physical-key pathway opens large cards without camera',!!switchBoard&&!state.camera);
    const frappeIndex=switchBoard.items.findIndex(r=>r.element.id==='커피프라페');
    check('frappe is reachable in button pathway',frappeIndex>=0);
    for(let i=0;i<frappeIndex;i++)press('ArrowRight');
    press('Enter');check('button selection requires confirmation',switchBoard.confirm);
    press('Enter');check('physical-key pathway orders frappe',$('kiosk').contentWindow.order_list.some(r=>r.name==='커피프라페'));
    $('kiosk').contentWindow.order_list=[];$('kiosk').contentWindow.open_order_list([]);item.click();await wait(600);
    switchView('sample');
    await until(()=>state.regions.length>0&&state.regions[0].key.startsWith('yolo'));
    check('real YOLO weights detect supplied image',state.regions.length>=5);
    check('YOLO boxes respect image viewport',state.regions.every(r=>r.w>0&&r.h>0&&r.x>=0&&r.y>=0));
    const sampleBoxes=state.regions.length;
    switchView('kiosk');await wait(600);
    $('regionMode').value='yolo';invalidateRegions();
    await until(()=>$('regionCount').textContent.includes('YOLO'),30000);
    check('real model also processes native kiosk snapshot',state.regions.every(r=>r.w>0&&r.h>0));
    const kioskBoxes=state.regions.length;
    $('regionMode').value='dom';invalidateRegions();await wait(500);
    // Test calibration UI and tracking injection without opening a real camera.
    $('dwell').checked=false;
    const sent=[];send=(cmd,args={})=>sent.push({cmd,...args});
    receive({type:'started'});beginCalibration();
    check('calibration button opens overlay',state.calibrating&&!$('calibration').hidden);
    receive({type:'calibration_started',generation:state.calGeneration});
    for(let i=0;i<CAL.length;i++)receive({type:'sample_done',phase:'calibrate',index:i,generation:state.calGeneration});
    check('9-point calibration advances to independent validation',state.phase==='check'&&state.point===0);
    for(let i=0;i<CHECK.length-1;i++)receive({type:'sample_done',phase:'check',index:i,generation:state.calGeneration});
    receive({type:'calibration_result',generation:state.calGeneration,validation:{passed:true,mean_px:30,p95_px:55}});
    check('calibration result exposes measured errors',state.calibrated&&$('meanError').textContent==='30');
    $('closeResult').click();await wait(400);
    const target=state.regions.find(r=>r.element?.getAttribute('onclick')?.startsWith('option('));
    const trackEvent={type:'tracking',valid:true,x:target.x+target.w/2,y:target.y+target.h/2,reason:'테스트 입력',fps:30};
    for(let i=0;i<12;i++){receive(trackEvent);await wait(33);}
    check('tracking dispatches native cursor movement',sent.some(m=>m.cmd==='move_cursor'&&Math.abs(m.x-trackEvent.x)<2));
    check('gaze maps into kiosk target',state.active?.key===target.key&&!$('gaze').hidden);
    const beforeDwell=$('kiosk').contentWindow.total_list[0];
    $('dwell').checked=true;
    for(let i=0;i<42;i++){receive(i%8===7?{type:'tracking',valid:false,reason:'짧은 깜빡임'}:trackEvent);await wait(33);}
    await wait(500);
    const afterDwell=$('kiosk').contentWindow.total_list[0];
    check('dwell with brief face loss adds exactly one order',afterDwell===beforeDwell+1);
    receive(trackEvent);state.dwellStart=performance.now()-1300;receive(trackEvent);await wait(200);
    check('remaining gaze does not repeatedly order',$('kiosk').contentWindow.total_list[0]===afterDwell&&!!state.blockedRect);
    $('dwell').checked=false;
    receive({type:'tracking',valid:false,reason:'얼굴 미검출'});
    await wait(450);
    check('face loss clears target and cursor',state.active===null&&$('gaze').hidden);
    receive(trackEvent);pause();
    check('pause clears gaze',state.paused&&$('gaze').hidden);pause();
    beginCalibration();cancelCalibration();check('calibration can be cancelled',!state.calibrating&&$('calibration').hidden);
    receive({type:'calibration_invalid',message:'창 크기 변경'});
    check('window change invalidates old calibration',!state.calibrated);
    receive({type:'stopped'});send=realSend;
    $('meanError').textContent='—';$('p95Error').textContent='—';$('calBadge').textContent='보정 전';
    $('trackingHint').textContent='캘리브레이션을 누르면 카메라를 켜고 눈의 위치를 맞춥니다.';
    $('toast').hidden=true;switchView('kiosk');await wait(400);
    realSend('smoke_result',{passed:true,results,sample_boxes:sampleBoxes,kiosk_boxes:kioskBoxes});
  }catch(error){send=realSend;realSend('smoke_result',{passed:false,results,error:String(error),stack:error.stack,ready:state.ready,regions:state.regions.length,frameAccessible:!!$('kiosk').contentDocument});}
})();
